# Generated by Django 5.1.4 on 2025-01-12 00:38

import calorie_tracker.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('calories', calorie_tracker.models.PositiveDecimalField(decimal_places=2, max_digits=10)),
                ('fats', calorie_tracker.models.PositiveDecimalField(decimal_places=2, max_digits=10)),
                ('carbs', calorie_tracker.models.PositiveDecimalField(decimal_places=2, max_digits=10)),
                ('proteins', calorie_tracker.models.PositiveDecimalField(decimal_places=2, max_digits=10)),
                ('portion_size', calorie_tracker.models.PositiveDecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('food_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calorie_tracker.food')),
                ('barcode', models.CharField(blank=True, max_length=64)),
            ],
            bases=('calorie_tracker.food',),
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('weight', calorie_tracker.models.PositiveDecimalField(decimal_places=2, max_digits=10)),
                ('meal_time', models.IntegerField(choices=[(1, 'Breakfast'), (2, 'Second Breakfast'), (3, 'Lunch'), (4, 'Dinner'), (5, 'Supper')])),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meals', to='calorie_tracker.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', calorie_tracker.models.PositiveDecimalField(decimal_places=2, max_digits=10)),
                ('base_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='calorie_tracker.product')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('food_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calorie_tracker.food')),
                ('ingredients', models.ManyToManyField(related_name='recipies', to='calorie_tracker.ingredient')),
            ],
            bases=('calorie_tracker.food',),
        ),
    ]
