# Generated by Django 5.1.5 on 2025-02-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_tracker', '0003_alter_meal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
